// Automatically generated by: ::SceMiMsg
// DO NOT EDIT
// C++ Class with SceMi Message passing for Bluespec type:  Types::Addr
// Generated on: Mon Dec 22 14:41:16 CST 2014
// Bluespec version: 2014.07.A 2014-07-30 34078

#pragma once

#include "bsv_scemi.h"


/// An alias or typedef name for BitT<32> to Addr
typedef BitT<32> Addr ;

