// Automatically generated by: ::SceMiMsg
// DO NOT EDIT
// C++ Class with SceMi Message passing for Bluespec type:  ProcTypes::RIndx
// Generated on: Mon Dec 22 14:41:16 CST 2014
// Bluespec version: 2014.07.A 2014-07-30 34078

#pragma once

#include "bsv_scemi.h"


/// An alias or typedef name for BitT<5> to RIndx
typedef BitT<5> RIndx ;

