// This file automatically generated by SceMiParams::genProbeFile
// DO NOT EDIT
// Generated on: Mon Dec 22 14:41:14 CST 2014
// Bluespec version: 2014.07.A 2014-07-30 34078

#include "bsv_scemi.h"


BSVType *ProbesXactor::createData(unsigned int probeNum, Packet *data, SceMiU64 cycle)
{
  BSVType *type = NULL;
 // No probes are defined!

  return type;
}

unsigned int ProbesXactor::getBitSize(unsigned int probeNum)
{
  return 0;
}

