// Automatically generated by: ::SceMiMsg
// DO NOT EDIT
// C++ Class with SceMi Message passing for Bluespec type:  SceMiLayer::ToHost
// Generated on: Mon Dec 22 14:41:14 CST 2014
// Bluespec version: 2014.07.A 2014-07-30 34078

#pragma once

#include "bsv_scemi.h"
#include "Tuple2_Bit_5_Bit_32.h"


/// An alias or typedef name for Tuple2_Bit_5_Bit_32 to ToHost
typedef Tuple2_Bit_5_Bit_32 ToHost ;

