/*
 * Generated by Bluespec Compiler, version 2014.07.A (build 34078, 2014-07-30)
 * 
 * On Mon Dec 22 14:39:49 CST 2014
 * 
 */
extern "C" {
  void bluenoc_close_tcp_socket(unsigned int );
  unsigned int bluenoc_open_tcp_socket(unsigned int );
  void bluenoc_recv_tcp_beat(unsigned int *, unsigned int , char , char , unsigned int *);
  char bluenoc_send_tcp_beat(unsigned int , char , char , unsigned int *);
}
