/*
 * Generated by Bluespec Compiler, version 2014.07.A (build 34078, 2014-07-30)
 * 
 * On Mon Dec 22 14:39:49 CST 2014
 * 
 */

/* Generation options: keep-fires */
#ifndef __module_brAddrCalc_h__
#define __module_brAddrCalc_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the module_brAddrCalc module */
class MOD_module_brAddrCalc : public Module {
 
 /* Clock handles */
 private:
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
 
 /* Constructor */
 public:
  MOD_module_brAddrCalc(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
 
 /* Port definitions */
 public:
  tUInt32 PORT_brAddrCalc_pc;
  tUInt32 PORT_brAddrCalc_val;
  tUInt8 PORT_brAddrCalc_iType;
  tUInt32 PORT_brAddrCalc_imm;
  tUInt8 PORT_brAddrCalc_taken;
  tUInt32 PORT_brAddrCalc;
  tUInt8 PORT_RDY_brAddrCalc;
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_CAN_FIRE_brAddrCalc;
 
 /* Local definitions */
 private:
 
 /* Rules */
 public:
 
 /* Methods */
 public:
  tUInt32 METH_brAddrCalc(tUInt32 ARG_brAddrCalc_pc,
			  tUInt32 ARG_brAddrCalc_val,
			  tUInt8 ARG_brAddrCalc_iType,
			  tUInt32 ARG_brAddrCalc_imm,
			  tUInt8 ARG_brAddrCalc_taken);
  tUInt8 METH_RDY_brAddrCalc();
 
 /* Reset routines */
 public:
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_module_brAddrCalc &backing);
  void vcd_defs(tVCDDumpType dt, MOD_module_brAddrCalc &backing);
};

#endif /* ifndef __module_brAddrCalc_h__ */
